export const DEPARTMENTS = [
  'Amazonas', 'Antioquia', 'Arauca', 'Atlántico', 'Bogotá D.C.', 'Bolívar', 'Boyacá', 
  'Caldas', 'Caquetá', 'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Córdoba', 'Cundinamarca', 
  'Guainía', 'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño', 
  'Norte de Santander', 'Putumayo', 'Quindío', 'Risaralda', 'San Andrés y Providencia', 
  'Santander', 'Sucre', 'Tolima', 'Valle del Cauca', 'Vaupés', 'Vichada'
];

export const MUNICIPALITIES = [
  { name: 'Leticia', dept: 'Amazonas' },
  { name: 'Puerto Nariño', dept: 'Amazonas' },
  { name: 'Medellín', dept: 'Antioquia' },
  { name: 'Bello', dept: 'Antioquia' },
  { name: 'Itagüí', dept: 'Antioquia' },
  { name: 'Envigado', dept: 'Antioquia' },
  { name: 'Apartadó', dept: 'Antioquia' },
  { name: 'Rionegro', dept: 'Antioquia' },
  { name: 'Caucasia', dept: 'Antioquia' },
  { name: 'Turbo', dept: 'Antioquia' },
  { name: 'Arauca', dept: 'Arauca' },
  { name: 'Arauquita', dept: 'Arauca' },
  { name: 'Tame', dept: 'Arauca' },
  { name: 'Barranquilla', dept: 'Atlántico' },
  { name: 'Soledad', dept: 'Atlántico' },
  { name: 'Malambo', dept: 'Atlántico' },
  { name: 'Sabanalarga', dept: 'Atlántico' },
  { name: 'Puerto Colombia', dept: 'Atlántico' },
  { name: 'Bogotá D.C.', dept: 'Bogotá D.C.' },
  { name: 'Cartagena de Indias', dept: 'Bolívar' },
  { name: 'Magangué', dept: 'Bolívar' },
  { name: 'Turbaco', dept: 'Bolívar' },
  { name: 'Arjona', dept: 'Bolívar' },
  { name: 'Tunja', dept: 'Boyacá' },
  { name: 'Duitama', dept: 'Boyacá' },
  { name: 'Sogamoso', dept: 'Boyacá' },
  { name: 'Manizales', dept: 'Caldas' },
  { name: 'La Dorada', dept: 'Caldas' },
  { name: 'Florencia', dept: 'Caquetá' },
  { name: 'Yopal', dept: 'Casanare' },
  { name: 'Popayán', dept: 'Cauca' },
  { name: 'Santander de Quilichao', dept: 'Cauca' },
  { name: 'Valledupar', dept: 'Cesar' },
  { name: 'Aguachica', dept: 'Cesar' },
  { name: 'Quibdó', dept: 'Chocó' },
  { name: 'Montería', dept: 'Córdoba' },
  { name: 'Cereté', dept: 'Córdoba' },
  { name: 'Sahagún', dept: 'Córdoba' },
  { name: 'Lorica', dept: 'Córdoba' },
  { name: 'Soacha', dept: 'Cundinamarca' },
  { name: 'Girardot', dept: 'Cundinamarca' },
  { name: 'Zipaquirá', dept: 'Cundinamarca' },
  { name: 'Facatativá', dept: 'Cundinamarca' },
  { name: 'Fusagasugá', dept: 'Cundinamarca' },
  { name: 'Chía', dept: 'Cundinamarca' },
  { name: 'Inírida', dept: 'Guainía' },
  { name: 'San José del Guaviare', dept: 'Guaviare' },
  { name: 'Neiva', dept: 'Huila' },
  { name: 'Pitalito', dept: 'Huila' },
  { name: 'Riohacha', dept: 'La Guajira' },
  { name: 'Maicao', dept: 'La Guajira' },
  { name: 'Santa Marta', dept: 'Magdalena' },
  { name: 'Ciénaga', dept: 'Magdalena' },
  { name: 'Villavicencio', dept: 'Meta' },
  { name: 'Acacías', dept: 'Meta' },
  { name: 'Pasto', dept: 'Nariño' },
  { name: 'Ipiales', dept: 'Nariño' },
  { name: 'Tumaco', dept: 'Nariño' },
  { name: 'Cúcuta', dept: 'Norte de Santander' },
  { name: 'Ocaña', dept: 'Norte de Santander' },
  { name: 'Villa del Rosario', dept: 'Norte de Santander' },
  { name: 'Mocoa', dept: 'Putumayo' },
  { name: 'Armenia', dept: 'Quindío' },
  { name: 'Pereira', dept: 'Risaralda' },
  { name: 'Dosquebradas', dept: 'Risaralda' },
  { name: 'San Andrés', dept: 'San Andrés y Providencia' },
  { name: 'Bucaramanga', dept: 'Santander' },
  { name: 'Floridablanca', dept: 'Santander' },
  { name: 'Barrancabermeja', dept: 'Santander' },
  { name: 'Girón', dept: 'Santander' },
  { name: 'Sincelejo', dept: 'Sucre' },
  { name: 'Sincé', dept: 'Sucre' },
  { name: 'Corozal', dept: 'Sucre' },
  { name: 'Sampues', dept: 'Sucre' },
  { name: 'Tolú', dept: 'Sucre' },
  { name: 'Ibagué', dept: 'Tolima' },
  { name: 'Espinal', dept: 'Tolima' },
  { name: 'Cali', dept: 'Valle del Cauca' },
  { name: 'Buenaventura', dept: 'Valle del Cauca' },
  { name: 'Palmira', dept: 'Valle del Cauca' },
  { name: 'Tuluá', dept: 'Valle del Cauca' },
  { name: 'Cartago', dept: 'Valle del Cauca' },
  { name: 'Jamundí', dept: 'Valle del Cauca' },
  { name: 'Buga', dept: 'Valle del Cauca' },
  { name: 'Yumbo', dept: 'Valle del Cauca' },
  { name: 'Mitu', dept: 'Vaupés' },
  { name: 'Puerto Carreño', dept: 'Vichada' }
];

export const BARRIOS_BY_CITY: Record<string, string[]> = {
  'Sincelejo': [
    '2 de Septiembre', 'Las Canarias', 'Ciudad Satélite', 'Los Laureles', 'Pablo VI',
    'Divino Salvador', 'San Rafael', 'El Rubí', 'Todo Poderoso', 'La Estrella',
    'Vallejo', 'La Pollita', 'Villa Orieta', 'La Selva', 'Virgen del Carmen',
    'Media Luna', 'Calle Sucre', 'Camilo Torres', 'Ipanema', '20 de Enero',
    'La Independencia', '6 de Febrero', 'La Terraza I', '20 de Julio I',
    'Alfonso López', '20 de Julio II', 'California', 'España', 'José Germán',
    '7 de Agosto', 'Cuatro Vientos', 'Antonio de la Torre', 'El Cauca', 'La Lucha',
    'La María', '17 de Septiembre', 'La Vega', '6 de Enero', 'Los Rosales',
    'Boston', 'Margaritas II', 'Cecar', 'Medellín', 'Antonio Nariño',
    'Gran Colombia', 'Divino Niño', 'La Campiña', 'Normandía', 'Nueva Esperanza',
    'El Cortijo', 'San José', 'Los Alpes', 'Venecia', 'La Ford', 'La Pajuela',
    'Mochila', 'Majagual'
  ],
  'Medellín': ['El Poblado', 'Laureles', 'Belén', 'Envigado', 'Aranjuez', 'Manrique'],
  'Bogotá D.C.': ['Suba', 'Usaquén', 'Chapinero', 'Bosa', 'Engativá', 'Kennedy', 'Fontibón'],
  'Barranquilla': ['El Prado', 'Alto Prado', 'Ciudad Jardín', 'Boston', 'Recreo']
};

export const ALL_CITIES = MUNICIPALITIES.map(m => ({
  label: `${m.name}, ${m.dept} - Colombia`,
  name: m.name,
  department: m.dept,
  neighborhoods: BARRIOS_BY_CITY[m.name] || []
}));
